// AI Tools Data
const tools = [
    {
        id: 'claude',
        name: 'Claude',
        category: 'chatbot',
        description: 'Anthropic\'s conversational AI assistant with advanced reasoning and analysis capabilities',
        url: 'https://claude.ai',
        rating: 4.8,
        views: '10k+'
    },
    {
        id: 'deepseek',
        name: 'DeepSeek',
        category: 'search',
        description: 'Advanced AI platform for deep search and analysis of complex data',
        url: 'https://deepseek.ai',
        rating: 4.8,
        views: '10k+'
    },
    {
        id: 'doubao',
        name: 'Doubao AI',
        category: 'chatbot',
        description: 'Chinese AI assistant for conversation, content creation and analysis',
        url: 'https://doubao.com',
        rating: 4.8,
        views: '10k+'
    },
    {
        id: 'gemini',
        name: 'Gemini',
        category: 'chatbot',
        description: 'Google\'s multimodal AI model capable of understanding and generating text, code, math, and more',
        url: 'https://gemini.google.com',
        rating: 4.8,
        views: '10k+'
    },
    {
        id: 'midjourney',
        name: 'Midjourney',
        category: 'image',
        description: 'AI image generator creating detailed photorealistic and artistic images',
        url: 'https://www.midjourney.com',
        rating: 4.8,
        views: '10k+'
    },
    {
        id: 'chatgpt',
        name: 'ChatGPT',
        category: 'chatbot',
        description: 'OpenAI\'s powerful language model for natural conversations and content generation',
        url: 'https://chat.openai.com',
        rating: 4.9,
        views: '100k+'
    },
    {
        id: 'dall-e',
        name: 'DALL·E',
        category: 'image',
        description: 'OpenAI\'s AI system that creates realistic images and art from natural language descriptions',
        url: 'https://openai.com/dall-e-3',
        rating: 4.8,
        views: '50k+'
    },
    {
        id: 'stable-diffusion',
        name: 'Stable Diffusion',
        category: 'image',
        description: 'Open-source AI art generator creating high-quality images from text descriptions',
        url: 'https://stability.ai',
        rating: 4.7,
        views: '30k+'
    },
    {
        id: 'copilot',
        name: 'GitHub Copilot',
        category: 'coding',
        description: 'AI pair programmer that helps you write better code faster',
        url: 'https://github.com/features/copilot',
        rating: 4.8,
        views: '20k+'
    },
    {
        id: 'cursor',
        name: 'Cursor',
        category: 'coding',
        description: 'AI-first code editor that helps you write, edit and understand code',
        url: 'https://cursor.sh',
        rating: 4.7,
        views: '15k+'
    }
];

// Featured Tools Data
const featuredTools = [
    {
        id: 'ifable',
        name: 'iFable',
        description: 'Your personal anime universe, generated by AI',
        url: 'https://ifable.ai'
    },
    {
        id: 'soul-machines',
        name: 'Soul Machines',
        description: 'Global leader in humanizing AI experiences',
        url: 'https://www.soulmachines.com'
    },
    {
        id: 'salesape',
        name: 'SalesAPE AI',
        description: 'Your AI sales representative - available 24/7',
        url: 'https://www.salesape.ai'
    }
];

// Category colors for icons
const categoryColors = {
    chatbot: { bg: '#e0f2fe', color: '#0ea5e9' },
    image: { bg: '#fef3c7', color: '#d97706' },
    video: { bg: '#fce7f3', color: '#db2777' },
    audio: { bg: '#f3e8ff', color: '#9333ea' },
    writing: { bg: '#dcfce7', color: '#16a34a' },
    coding: { bg: '#dbeafe', color: '#2563eb' },
    marketing: { bg: '#ffe4e6', color: '#e11d48' },
    design: { bg: '#f3f4f6', color: '#4b5563' },
    search: { bg: '#f0fdf4', color: '#15803d' }
};

// Get favicon URL for a website
function getFaviconUrl(url) {
    try {
        const domain = new URL(url).hostname;
        return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
    } catch (error) {
        return '/images/default-icon.png';
    }
}

// Create tool card HTML
function createToolCard(tool) {
    const categoryStyle = categoryColors[tool.category] || { bg: '#f3f4f6', color: '#4b5563' };
    const iconUrl = getFaviconUrl(tool.url);
    
    return `
        <div class="tool-card" data-category="${tool.category}" onclick="window.open('${tool.url}', '_blank')">
            <div class="tool-header">
                <div class="tool-icon" style="background: ${categoryStyle.bg}">
                    <img src="${iconUrl}" alt="${tool.name}" width="40" height="40" 
                         onerror="this.src='/images/default-icon.png'">
                </div>
                <div class="tool-info">
                    <h3>${tool.name}</h3>
                    <span class="tool-category" style="background: ${categoryStyle.bg}; color: ${categoryStyle.color}">
                        ${tool.category}
                    </span>
                </div>
            </div>
            <p class="tool-description">${tool.description}</p>
            <div class="tool-meta">
                <span class="tool-rating">
                    <i class="fas fa-star" style="color: #eab308"></i>
                    ${tool.rating}
                </span>
                <span class="tool-views">
                    <i class="fas fa-eye"></i>
                    ${tool.views}
                </span>
            </div>
        </div>
    `;
}

// Create featured tool HTML
function createFeaturedTool(tool) {
    const iconUrl = getFaviconUrl(tool.url);
    return `
        <div class="featured-tool" onclick="window.open('${tool.url}', '_blank')">
            <img src="${iconUrl}" alt="${tool.name}" 
                 onerror="this.src='/images/default-icon.png'">
            <div class="featured-tool-info">
                <h3>${tool.name}</h3>
                <p>${tool.description}</p>
            </div>
        </div>
    `;
}

// Load tools into grid
function loadTools() {
    const toolsGrid = document.getElementById('tools-grid');
    if (!toolsGrid) return;

    const toolsHTML = tools.map(createToolCard).join('');
    toolsGrid.innerHTML = toolsHTML;
}

// Load featured tools
function loadFeaturedTools() {
    const featuredContainer = document.querySelector('.featured-tools');
    if (!featuredContainer) return;

    const featuredHTML = featuredTools.map(createFeaturedTool).join('');
    featuredContainer.innerHTML = featuredHTML;
}

// Filter tools by category
function filterTools(category) {
    const toolCards = document.querySelectorAll('.tool-card');
    toolCards.forEach(card => {
        if (!category || card.dataset.category === category) {
            card.style.display = 'block';
        } else {
            card.style.display = 'none';
        }
    });
}

// Add category click handlers
function initCategoryFilters() {
    const categoryLinks = document.querySelectorAll('.sidebar-nav a');
    categoryLinks.forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            const category = link.dataset.category;
            filterTools(category);
            
            // Update active state
            categoryLinks.forEach(l => l.classList.remove('active'));
            link.classList.add('active');
        });
    });
}

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    loadTools();
    loadFeaturedTools();
    initCategoryFilters();
}); 